cmd.do('fetch 1ehz, async=0;')
cmd.do('as cartoon;')
cmd.do('set cartoon_ladder_radius, 0.1;')
cmd.do('set cartoon_ladder_color, gray;')
cmd.do('set cartoon_nucleic_acid_mode, 1;')
cmd.do('dssr_block')
